{
  "uid" : "88394fffaf1a2549",
  "name" : "test_02_file[file_name_info0]",
  "fullName" : "TestCase.test_vue.Test_Login_Vue#test_02_file",
  "historyId" : "4f977ac249d94f9cc2eae1e786cb6e41",
  "time" : {
    "start" : 1647309360701,
    "stop" : 1647309360701,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ValueError: too many values to unpack (expected 5)",
  "statusTrace" : "self = <TestCase.test_vue.Test_Login_Vue object at 0x7fcd805a1f70>\nfile_name_info = [1, '输入正确的文件名，提示下载成功', 0, 'y', None, None]\n\n    @pytest.mark.parametrize(\"file_name_info\", read_excel(\"./Data/data.xlsx\", \"export\"))\n    def test_02_file(self, file_name_info):\n        # print(file_name_info)\n>       index, case_name, file_name, is_exe, result = file_name_info\nE       ValueError: too many values to unpack (expected 5)\n\nTestCase/test_vue.py:36: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1647309349526,
      "stop" : 1647309351402,
      "duration" : 1876
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1647309360716,
      "stop" : 1647309362728,
      "duration" : 2012
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=99.0.4844.51)\nStacktrace:\n0   chromedriver                        0x00000001090dfee9 chromedriver + 5013225\n1   chromedriver                        0x000000010906b1d3 chromedriver + 4534739\n2   chromedriver                        0x0000000108c41a68 chromedriver + 170600\n3   chromedriver                        0x0000000108c2310e chromedriver + 45326\n4   chromedriver                        0x0000000108c96dbc chromedriver + 519612\n5   chromedriver                        0x0000000108c9b15e chromedriver + 536926\n6   chromedriver                        0x0000000108c937a8 chromedriver + 505768\n7   chromedriver                        0x0000000108c6976e chromedriver + 333678\n8   chromedriver                        0x0000000108c6a745 chromedriver + 337733\n9   chromedriver                        0x000000010909befe chromedriver + 4734718\n10  chromedriver                        0x00000001090b5a19 chromedriver + 4839961\n11  chromedriver                        0x00000001090bb1c8 chromedriver + 4862408\n12  chromedriver                        0x00000001090b63aa chromedriver + 4842410\n13  chromedriver                        0x0000000109090a01 chromedriver + 4688385\n14  chromedriver                        0x00000001090d1538 chromedriver + 4953400\n15  chromedriver                        0x00000001090d16c1 chromedriver + 4953793\n16  chromedriver                        0x00000001090e7225 chromedriver + 5042725\n17  libsystem_pthread.dylib             0x00007fff2030f8fc _pthread_start + 224\n18  libsystem_pthread.dylib             0x00007fff2030b443 thread_start + 15\n\n",
    "statusTrace" : "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/TestCase/test_vue.py\", line 51, in teardown_class\n    self.driver.close()\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "TestCase"
  }, {
    "name" : "suite",
    "value" : "test_vue"
  }, {
    "name" : "subSuite",
    "value" : "Test_Login_Vue"
  }, {
    "name" : "host",
    "value" : "YZQ.local"
  }, {
    "name" : "thread",
    "value" : "2877-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "TestCase.test_vue"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "file_name_info",
    "value" : "[1, '输入正确的文件名，提示下载成功', 0, 'y', None, None]"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "88394fffaf1a2549.json",
  "parameterValues" : [ "[1, '输入正确的文件名，提示下载成功', 0, 'y', None, None]" ]
}