{
  "uid" : "d7284dd3c1946db",
  "name" : "test_02_file[file_name_info3]",
  "fullName" : "TestCase.test_vue.Test_Login_Vue#test_02_file",
  "historyId" : "df6b79103b7cc5fa2c7b5e44d096b15a",
  "time" : {
    "start" : 1647332889480,
    "stop" : 1647332889480,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ValueError: too many values to unpack (expected 5)",
  "statusTrace" : "self = <TestCase.test_vue.Test_Login_Vue object at 0x7fb49f3c1040>\nfile_name_info = [None, None, None, None, None, None]\n\n    @pytest.mark.parametrize(\"file_name_info\", read_excel(\"./Data/data.xlsx\", \"export\"))\n    def test_02_file(self, file_name_info):\n        # print(file_name_info)\n>       index, case_name, file_name, is_exe, result = file_name_info\nE       ValueError: too many values to unpack (expected 5)\n\nTestCase/test_vue.py:33: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 6,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1647332882138,
      "stop" : 1647332883857,
      "duration" : 1719
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1647332889483,
      "stop" : 1647332891638,
      "duration" : 2155
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "TestCase"
  }, {
    "name" : "suite",
    "value" : "test_vue"
  }, {
    "name" : "subSuite",
    "value" : "Test_Login_Vue"
  }, {
    "name" : "host",
    "value" : "localhost"
  }, {
    "name" : "thread",
    "value" : "10808-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "TestCase.test_vue"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "file_name_info",
    "value" : "[None, None, None, None, None, None]"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "d9bc0f51dc0287c3",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service chromedriver",
      "time" : {
        "start" : 1647331833470,
        "stop" : 1647331833470,
        "duration" : 0
      }
    }, {
      "uid" : "998362d8e57dbb1b",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service chromedriver",
      "time" : {
        "start" : 1647331748472,
        "stop" : 1647331748472,
        "duration" : 0
      }
    }, {
      "uid" : "5a446d58192db398",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service chromedriver",
      "time" : {
        "start" : 1647331604462,
        "stop" : 1647331604462,
        "duration" : 0
      }
    }, {
      "uid" : "1a9fe8755988212",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service chromedriver",
      "time" : {
        "start" : 1647331512631,
        "stop" : 1647331512631,
        "duration" : 0
      }
    }, {
      "uid" : "9366f973bf143a8",
      "status" : "broken",
      "statusDetails" : "ValueError: too many values to unpack (expected 5)",
      "time" : {
        "start" : 1647309470977,
        "stop" : 1647309470977,
        "duration" : 0
      }
    }, {
      "uid" : "33dcafbb56132660",
      "status" : "broken",
      "statusDetails" : "ValueError: too many values to unpack (expected 5)",
      "time" : {
        "start" : 1647309360713,
        "stop" : 1647309360713,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "d7284dd3c1946db.json",
  "parameterValues" : [ "[None, None, None, None, None, None]" ]
}